---
abstract: 'Perform diffs on files and record sets'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.02, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Diff
no_index:
  directory:
    - t
    - inc
requires:
  Algorithm::Diff: '1.19'
  Exporter: '0'
  perl: '5.006'
resources:
  repository: https://github.com/Ovid/Text-Diff
version: 1.41_01
